name = "FlicsFlow"
uuid = "23c7c6bd-9573-4f01-9176-583f16e76a65"
authors = ["Mohamad Arif Andira <arifandira0209@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
